In [1]:
#Import Libraries

import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split

In [2]:
#Load Cleaned Data

df = pd.read_csv("D:/customer-churn-capstone/data/processed/churn_cleaned.csv")
df.head()

,Tenure,MonthlyCharges,TotalCharges,Contract,PaymentMethod,PaperlessBilling,SeniorCitizen,Churn
0,6,64,1540,One year,Credit Card,No,1,0
1,21,113,1753,Month-to-month,Electronic Check,Yes,1,0
2,27,31,1455,Two year,Credit Card,No,1,0
3,53,29,7150,Month-to-month,Electronic Check,No,1,0
4,16,185,1023,One year,Electronic Check,No,1,0

In [3]:
#Separate Features and Target

X = df.drop("Churn", axis=1)
y = df["Churn"]

In [4]:
print("Before Encoding:")
print(df.dtypes)

Before Encoding:
Tenure               int64
MonthlyCharges       int64
TotalCharges         int64
Contract            object
PaymentMethod       object
PaperlessBilling    object
SeniorCitizen        int64
Churn                int64
dtype: object

In [5]:
#Encode Categorical Variables

X = pd.get_dummies(X, drop_first=True)
X.head()

,Tenure,MonthlyCharges,TotalCharges,SeniorCitizen,Contract_One year,Contract_Two year,PaymentMethod_Credit Card,PaymentMethod_Electronic Check,PaperlessBilling_Yes
0,6,64,1540,1,True,False,True,False,False
1,21,113,1753,1,False,False,False,True,True
2,27,31,1455,1,False,True,True,False,False
3,53,29,7150,1,False,False,False,True,False
4,16,185,1023,1,True,False,False,True,False

In [6]:
X = X.astype(int)
X.dtypes

Tenure                            int64
MonthlyCharges                    int64
TotalCharges                      int64
SeniorCitizen                     int64
Contract_One year                 int64
Contract_Two year                 int64
PaymentMethod_Credit Card         int64
PaymentMethod_Electronic Check    int64
PaperlessBilling_Yes              int64
dtype: object

In [7]:
#Train-Test Split

X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

In [8]:
X_train.shape, X_test.shape

((400, 9), (100, 9))

In [9]:
#Handle Class Imbalance

class_weight="balanced"

In [10]:
X_train.to_csv("../data/processed/X_train.csv", index=False)
X_test.to_csv("../data/processed/X_test.csv", index=False)
y_train.to_csv("../data/processed/y_train.csv", index=False)
y_test.to_csv("../data/processed/y_test.csv", index=False)